### ISSUE TITLE
ModernAsyncTask #1

### ISSUE THREAD

**Issue by tylerstrickland-ts** [santhoshvai/omdb-android-client#4]
For months this has been working for me. Randomly it now doesnt work. I did not change any code. I'm not sure what's going on

2019-12-28 11:23:34.964 29269-29472/com.tetravalence.digitalcontent E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: com.tetravalence.digitalcontent, PID: 29269
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.IllegalStateException: Already executed.
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:159)
        at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall.execute(DefaultCallAdapterFactory.java:104)
        at com.tetravalence.digitalcontent.OMdBRetrofit.SearchService.performSearch(SearchService.java:311)
        at com.tetravalence.digitalcontent.OMdBRetrofit.RetrofitLoader.loadInBackground(RetrofitLoader.java:26)
        at com.tetravalence.digitalcontent.OMdBRetrofit.RetrofitLoader.loadInBackground(RetrofitLoader.java:9)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by tylerstrickland-ts** [comment]
2019-12-28 10:44:35.059 16287-16536/info.santhosh.omdbsearchclient E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
    Process: info.santhosh.omdbsearchclient, PID: 16287
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String info.santhosh.omdbsearchclient.omdbApiRetrofitService.searchService$Result.totalResults' on a null object reference
        at info.santhosh.omdbsearchclient.omdbApiRetrofitService.searchService$ResultWithDetail.<init>(searchService.java:35)
        at info.santhosh.omdbsearchclient.omdbApiRetrofitService.RetrofitLoader.loadInBackground(RetrofitLoader.java:30)
        at info.santhosh.omdbsearchclient.omdbApiRetrofitService.RetrofitLoader.loadInBackground(RetrofitLoader.java:12)
        at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:306)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:59)
        at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:47)
        at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)
